[date]
date_format = "%Y-%m-%d %H:%M"  # %Y: year, %m: month, %d: day, %H: hour, %M: minute. 시간은 항상 UTC 기준

[repo]
include_public_repos = true  # 공개 레포지토리의 개수를 카운트에 포함할지
include_private_repos = true  # 비공개 레포지토리의 개수를 카운트에 포함할지
include_collaborator_repo = true  # 협업자로 포함된 비공개 레포지토리나 접근 가능한 조직의 레포지토리의 개수를 포함할지
# 카드에 표시할 형식을 설정
# - "detail": 1 public, 2 private, 3 collabo repositories
#    - include_xxx_repos 설정이 false인 항목은 제외되어 표시됨
# - "total": Total 6 repositories
show_mode = "detail"

[commit]
include_private_commit = true  # TODO 비공개 레포지토리의 커밋 개수를 포함할지
show_commit_this_year = true  # 올해 커밋 개수를 같이 표시할지

[pr]
# 카드에 표시할 형식을 설정
# - "each": 1 open, 2 closed(unmerged), 3 merged
# - "total": Total 6 PRs
show_mode = "each"  # TODO 구현 필요