name: Update Card

on:
  schedule:
    - cron: "0 0 * * *"  # every 00:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update card
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python update-stats.py

      - name: Commit and push
        run: |
          git clone https://${{ secrets.TOKEN }}@github.com/${{ secrets.USER_NAME }}/${{ secrets.USER_NAME }}.git tmp
          cp ./result.svg ./tmp/result.svg
          cd tmp
          
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          git add result.svg

          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update stat card"
          git push